# Generated by Django 4.2.6 on 2023-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='end_term_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mid_term_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='ppt_completed',
            field=models.BooleanField(default=False),
        ),
    ]
