# Generated by Django 4.2.6 on 2023-11-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_course_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='course',
            name='lab_files_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='notes_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
